// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs3v9_okd3YXXcFqD4Ser8q3HE_xe9qzA',
    appId: '1:829072924686:android:53a3c1310dbd0e2d741c5f',
    messagingSenderId: '829072924686',
    projectId: 'future-ai-dff4a',
    storageBucket: 'future-ai-dff4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc-Cd1xWl_Nebf4qImZeRnk4j8WvLzopU',
    appId: '1:829072924686:ios:2a0037bb70f61419741c5f',
    messagingSenderId: '829072924686',
    projectId: 'future-ai-dff4a',
    storageBucket: 'future-ai-dff4a.appspot.com',
    androidClientId:
        '829072924686-pjgtuhf3r1uvaer80vs3etb0146kdjtd.apps.googleusercontent.com',
    iosClientId:
        '829072924686-87nuus5pouo2b4f3trbafk7cn3adj29p.apps.googleusercontent.com',
    iosBundleId: 'com.realjarvis.futureai',
  );
}
